var FRF = [
{Name:"Ugin, the Spirit Dragon", Cost:"8", Color:["C"], Rarity:"M", Type:["P"], Rating:"10", Sort:"1", Set:"FRF", Number:"1", Image:"/Images/FRF/Ugin--theSpiritDragon.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"2", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"3", Image:"/Images/FRF/.jpg"},
{Name:"Lightform", Cost:"1WW", Color:["W"], Rarity:"U", Type:["E"], Rating:"7", Sort:"1", Set:"FRF", Number:"4", Image:"/Images/FRF/Lightform.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"5", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"6", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"7", Image:"/Images/FRF/.jpg"},
{Name:"Citadel Siege", Cost:"2WW", Color:["W"], Rarity:"R", Type:["E"], Rating:"8", Sort:"1", Set:"FRF", Number:"8", Image:"/Images/FRF/CitadelSiege.jpg"},
{Name:"Daghatar the Adamant", Cost:"3W", Color:["W"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"FRF", Number:"9", Image:"/Images/FRF/DaghatartheAdamant.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"10", Image:"/Images/FRF/.jpg"},
{Name:"Dragonscale General", Cost:"3W", Color:["W"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"FRF", Number:"11", Image:"/Images/FRF/DragonscaleGeneral.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"12", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"13", Image:"/Images/FRF/.jpg"},
{Name:"Honor's Reward", Cost:"2W", Color:["W"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"FRF", Number:"14", Image:"/Images/FRF/HonorsReward.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"15", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"16", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"17", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"18", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"19", Image:"/Images/FRF/.jpg"},
{Name:"Monastery Mentor", Cost:"2W", Color:["W"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"20", Image:"/Images/FRF/MonasteryMentor.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"21", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"22", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"23", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"24", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"25", Image:"/Images/FRF/.jpg"},
{Name:"Soul Summons", Cost:"1W", Color:["W"], Rarity:"C", Type:["S"], Rating:"5", Sort:"1", Set:"FRF", Number:"26", Image:"/Images/FRF/SoulSummons.jpg"},
{Name:"Soulfire Grand Master", Cost:"1W", Color:["W"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"27", Image:"/Images/FRF/SoulfireGrandMaster.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"28", Image:"/Images/FRF/.jpg"},
{Name:"Valorous Stance", Cost:"1W", Color:["W"], Rarity:"U", Type:["I"], Rating:"8", Sort:"1", Set:"FRF", Number:"29", Image:"/Images/FRF/ValorousStance.jpg"},
{Name:"Wandering Champion", Cost:"1W", Color:["W"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"FRF", Number:"30", Image:"/Images/FRF/WanderingChampion.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"31", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"32", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"33", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"34", Image:"/Images/FRF/.jpg"},
{Name:"Jeskai Infiltrator", Cost:"2U", Color:["U"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"35", Image:"/Images/FRF/JeskaiInfiltrator.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"36", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"37", Image:"/Images/FRF/.jpg"},
{Name:"Jeskai Sage", Cost:"1U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"FRF", Number:"38", Image:"/Images/FRF/JeskaiSage.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"39", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"40", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"41", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"42", Image:"/Images/FRF/.jpg"},
{Name:"Monastery Siege", Cost:"2U", Color:["U"], Rarity:"R", Type:["E"], Rating:"7", Sort:"1", Set:"FRF", Number:"43", Image:"/Images/FRF/MonasterySiege.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"44", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"45", Image:"/Images/FRF/.jpg"},
{Name:"Marang River Prowler", Cost:"2U", Color:["U"], Rarity:"U", Type:["C"], Rating:"8", Sort:"1", Set:"FRF", Number:"46", Image:"/Images/FRF/MarangRiverProwler.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"47", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"48", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"49", Image:"/Images/FRF/.jpg"},
{Name:"Sage-Eye Avengers", Cost:"4UU", Color:["U"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"FRF", Number:"50", Image:"/Images/FRF/Sage-EyeAvengers.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"51", Image:"/Images/FRF/.jpg"},
{Name:"Shu Yun, the Silent Tempest", Cost:"2U", Color:["U"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"FRF", Number:"52", Image:"/Images/FRF/ShuYun--theSilentTempest.jpg"},
{Name:"Supplant Form", Cost:"4UU", Color:["U"], Rarity:"R", Type:["I"], Rating:"7", Sort:"1", Set:"FRF", Number:"53", Image:"/Images/FRF/SupplantForm.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"54", Image:"/Images/FRF/.jpg"},
{Name:"Temporal Trespass", Cost:"8UUU", Color:["U"], Rarity:"M", Type:["S"], Rating:"9", Sort:"1", Set:"FRF", Number:"55", Image:"/Images/FRF/TemporalTrespass.jpg"},
{Name:"Torrent Elemental", Cost:"3UU", Color:["U"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"56", Image:"/Images/FRF/TorrentElemental.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"57", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"58", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"59", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"60", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"61", Image:"/Images/FRF/.jpg"},
{Name:"Archfiend of Depravity", Cost:"3BB", Color:["B"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"62", Image:"/Images/FRF/ArchfiendofDepravity.jpg"},
{Name:"Brutal Hordechief", Cost:"3B", Color:["B"], Rarity:"M", Type:["C"], Rating:"8", Sort:"1", Set:"FRF", Number:"63", Image:"/Images/FRF/BrutalHordechief.jpg"},
{Name:"Battle Brawler", Cost:"1B", Color:["B"], Rarity:"U", Type:["C"], Rating:"8", Sort:"1", Set:"FRF", Number:"64", Image:"/Images/FRF/BattleBrawler.jpg"},
{Name:"Crux of Fate", Cost:"3BB", Color:["B"], Rarity:"R", Type:["S"], Rating:"8", Sort:"1", Set:"FRF", Number:"65", Image:"/Images/FRF/CruxofFate.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"66", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"67", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"68", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"69", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"70", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"71", Image:"/Images/FRF/.jpg"},
{Name:"Gurmag Angler", Cost:"6B", Color:["B"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"FRF", Number:"72", Image:"/Images/FRF/GurmagAngler.jpg"},
{Name:"Hooded Assassin", Cost:"3B", Color:["B"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"FRF", Number:"73", Image:"/Images/FRF/HoodedAssassin.jpg"},
{Name:"Mardu Shadowspear", Cost:"0B", Color:["B"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"FRF", Number:"74", Image:"/Images/FRF/MarduShadowspear.jpg"},
{Name:"Mardu Strike Leader", Cost:"2B", Color:["B"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"FRF", Number:"75", Image:"/Images/FRF/MarduStrikeLeader.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"76", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"77", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"78", Image:"/Images/FRF/.jpg"},
{Name:"Palace Siege", Cost:"3BB", Color:["B"], Rarity:"R", Type:["E"], Rating:"7", Sort:"1", Set:"FRF", Number:"79", Image:"/Images/FRF/PalaceSiege.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"80", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"81", Image:"/Images/FRF/.jpg"},
{Name:"Soulflayer", Cost:"4BB", Color:["B"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"82", Image:"/Images/FRF/Soulflayer.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"83", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"84", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"85", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"86", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"87", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"88", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"89", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"90", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"91", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"92", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"93", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"94", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"95", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"96", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"97", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"98", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"99", Image:"/Images/FRF/.jpg"},
{Name:"Flamewake Phoenix", Cost:"1RR", Color:["R"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"100", Image:"/Images/FRF/FlamewakePhoenix.jpg"},
{Name:"Flamerush Rider", Cost:"4R", Color:["R"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"101", Image:"/Images/FRF/FlamerushRider.jpg"},
{Name:"Goblin Heelcutter", Cost:"3R", Color:["R"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"FRF", Number:"102", Image:"/Images/FRF/GoblinHeelcutter.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"103", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"104", Image:"/Images/FRF/.jpg"},
{Name:"Hungering Yeti", Cost:"4R", Color:["R"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"FRF", Number:"105", Image:"/Images/FRF/HungeringYeti.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"106", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"107", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"108", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"109", Image:"/Images/FRF/.jpg"},
{Name:"Outpost Siege", Cost:"3R", Color:["R"], Rarity:"R", Type:["E"], Rating:"9", Sort:"1", Set:"FRF", Number:"110", Image:"/Images/FRF/OutpostSiege.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"111", Image:"/Images/FRF/.jpg"},
{Name:"Rageform", Cost:"2RR", Color:["R"], Rarity:"U", Type:["E"], Rating:"7", Sort:"1", Set:"FRF", Number:"112", Image:"/Images/FRF/Rageform.jpg"},
{Name:"Shaman of the Great Hunt", Cost:"3R", Color:["R"], Rarity:"M", Type:["C"], Rating:"8", Sort:"1", Set:"FRF", Number:"113", Image:"/Images/FRF/ShamanoftheGreatHunt.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"114", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"115", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"116", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"117", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"118", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"119", Image:"/Images/FRF/.jpg"},
{Name:"Abzan Kin-Guard", Cost:"3G", Color:["G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"FRF", Number:"120", Image:"/Images/FRF/AbzanKin-Guard.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"121", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"122", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"123", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"124", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"125", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"126", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"127", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"128", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"129", Image:"/Images/FRF/.jpg"},
{Name:"Frontier Mastodon", Cost:"2G", Color:["G"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"FRF", Number:"130", Image:"/Images/FRF/FrontierMastodon.jpg"},
{Name:"Frontier Siege", Cost:"3G", Color:["G"], Rarity:"R", Type:["E"], Rating:"8", Sort:"1", Set:"FRF", Number:"131", Image:"/Images/FRF/FrontierSiege.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"132", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"133", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"134", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"135", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"136", Image:"/Images/FRF/.jpg"},
{Name:"Sandsteppe Mastodon", Cost:"5GG", Color:["G"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"FRF", Number:"137", Image:"/Images/FRF/SandsteppeMastodon.jpg"},
{Name:"Shamanic Revelation", Cost:"3GG", Color:["G"], Rarity:"R", Type:["S"], Rating:"7", Sort:"1", Set:"FRF", Number:"138", Image:"/Images/FRF/ShamanicRevelation.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"139", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"140", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"141", Image:"/Images/FRF/.jpg"},
{Name:"Temur War Shaman", Cost:"4GG", Color:["G"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"142", Image:"/Images/FRF/TemurWarShaman.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"143", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"144", Image:"/Images/FRF/.jpg"},
{Name:"Whisperwood Elemental", Cost:"3GG", Color:["G"], Rarity:"M", Type:["C"], Rating:"10", Sort:"1", Set:"FRF", Number:"145", Image:"/Images/FRF/WhisperwoodElemental.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"146", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"147", Image:"/Images/FRF/.jpg"},
{Name:"Yasova Dragonclaw", Cost:"2G", Color:["G"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"148", Image:"/Images/FRF/YasovaDragonclaw.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"149", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"150", Image:"/Images/FRF/.jpg"},
{Name:"Dromoka the Eternal", Cost:"3WG", Color:["W","G"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"151", Image:"/Images/FRF/DromokatheEternal.jpg"},
{Name:"Ethereal Ambush", Cost:"3GU", Color:["G","U"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"FRF", Number:"152", Image:"/Images/FRF/EtherealAmbush.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"153", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"154", Image:"/Images/FRF/.jpg"},
{Name:"Kolaghan, the Storm's Fury", Cost:"3BR", Color:["B","R"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"155", Image:"/Images/FRF/Kolaghan--theStormsFury.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"156", Image:"/Images/FRF/.jpg"},
{Name:"Silumgar, the Drifting Death", Cost:"4UB", Color:["U","B"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"FRF", Number:"157", Image:"/Images/FRF/Silumgar--theDriftingDeath.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"158", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"159", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"160", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"161", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"162", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"163", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"164", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"165", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"166", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"167", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"168", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"169", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"170", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"171", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"172", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"173", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"174", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"175", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"176", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"177", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"178", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"179", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"180", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"181", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"182", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"183", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"184", Image:"/Images/FRF/.jpg"},
{Name:"", Cost:"", Color:[], Rarity:"", Type:[], Rating:"", Sort:"1", Set:"FRF", Number:"185", Image:"/Images/FRF/.jpg"},
];